services:
  - type: web
    name: weatherlens
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd WeatherLens && gunicorn WeatherLens.wsgi:application"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        sync: false
      - key: WEATHER_API_KEY
        value: "4f11761b24243b03d59507095ac919f9"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "weatherlens.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://weatherlens.onrender.com"
      - key: ADMIN_USERNAME
        value: "jaikrishna"
      - key: ADMIN_PASSWORD
        value: "1234"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: POSTGRES_DB
        fromDatabase:
          name: weatherlens-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: weatherlens-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: weatherlens-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: weatherlens-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: weatherlens-postgres
          property: port
databases:
  - name: weatherlens-postgres
    plan: free

