services:
  - type: web
    name: weatherlens
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "bash -c 'cd WeatherLens && gunicorn WeatherLens.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --keep-alive 5'"
    healthCheckPath: "/health/"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        sync: false
      - key: WEATHER_API_KEY
        value: "4f11761b24243b03d59507095ac919f9"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "weatherlens-zqot.onrender.com,weatherlens.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://weatherlens-zqot.onrender.com"
      - key: ADMIN_USERNAME
        value: "jaikrishna"
      - key: ADMIN_PASSWORD
        value: "1234"
      - key: ADMIN_EMAIL
        value: "admin@example.com"

